### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by shabbir1215** [thehappydinoa/HQBot#1]
shows error

**Comment by thehappydinoa** [comment]
Did you set all the API keys? Did you install the dependencies? What's the error message?

**Comment by shabbir1215** [comment]
![28821939_1526056564186471_1234887974_o](https://user-images.githubusercontent.com/37163207/37170713-9902c2a2-22d9-11e8-8ce9-1a56081ac270.jpg)

**Comment by thehappydinoa** [comment]
Ah, ok that means that you do not have adb (Android Debugging Bridge) installed on your computer. Can you check and see if 
```
bot.py -vs
```
Works?

**Comment by shabbir1215** [comment]
i used bot.py -a during a live game deosnt work

**Comment by thehappydinoa** [comment]
@shabbir1215 it's because you don't have ADB installed orbin your PATH

**Comment by shabbir1215** [comment]
do u have a link to show me how to do that? it would be really helpful

**Comment by shabbir1215** [comment]
nvm just got adb gotta wait till next game see if it works

**Comment by thehappydinoa** [comment]
@shabbir1215 Glad you got it figured out, make sure to turn on USB Debugging in developer settings.

**Comment by shabbir1215** [comment]
Got adb and everything still doesn't work I think it might be cus of the update of the game

**Comment by thehappydinoa** [comment]
@shabbir1215 Please post your error message.

**Comment by shabbir1215** [comment]
[1;34m[?][1;m Click enter when question is on the screen
Error opening file: /sdcard/HQ/2018-03-12_00:58:14_1.png (No such file or directory)
remote object '/sdcard/HQ/2018-03-12_00:58:14_1.png' does not exist
[-] IOError: [Errno 22] Invalid argument: 'C:\\Users\\test\\Desktop\\HQBot-master\\2018-03-12_00:58:14_1.png'

C:\Users\test\Desktop\HQBot-master>fix thisssssssssssssssss
'fix' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\test\Desktop\HQBot-master>
C:\Users\test\Desktop\HQBot-master>bot.py -a
[1;33m[!][1;m Make sure your android device is connected via ADB

[1;34m[?][1;m Click enter when question is on the screen
Error opening file: /sdcard/HQ/2018-03-12_00:58:36_1.png (No such file or directory)
remote object '/sdcard/HQ/2018-03-12_00:58:36_1.png' does not exist
[-] IOError: [Errno 22] Invalid argument: 'C:\\Users\\test\\Desktop\\HQBot-master\\2018-03-12_00:58:36_1.png'

**Comment by thehappydinoa** [comment]
Ah I see what is happening

**Comment by shabbir1215** [comment]
What???

**Comment by thehappydinoa** [comment]
I'm working on a fix, but I think what is happening is that your phone doesn't have a HQ folder in the SDCARD

**Comment by shabbir1215** [comment]
Would I have to transfer my game to sd card?? Would that fix it??

**Comment by thehappydinoa** [comment]
Just making a folder at /sdcard/HQ/

**Comment by shabbir1215** [comment]
Ok ill try that at the 3 o clock game today

**Comment by thehappydinoa** [comment]
Ok if that doesn't work you will have to give me more info on your device

**Comment by shabbir1215** [comment]
[1;34m[?][1;m Click enter when question is on the screen
Error opening file: /sdcard/HQ/2018-03-12_19:04:23_1.png (No such file or directory)
remote object '/sdcard/HQ/2018-03-12_19:04:23_1.png' does not exist
[-] IOError: [Errno 22] Invalid argument: 'C:\\Users\\test\\Desktop\\HQBot-master\\2018-03-12_19:04:23_1.png' 
 

same error I have a s8+ running android 7.0

**Comment by thehappydinoa** [comment]
Did you run git pull?

**Comment by shabbir1215** [comment]
What's that

**Comment by thehappydinoa** [comment]
It's a git command that gets the most recent update.

**Comment by Shankdizzl3** [comment]
The issue still exists. Attempted to run the bot and ran into...

![untitled](https://user-images.githubusercontent.com/32983199/37379547-546e74e4-270a-11e8-9d7a-87d48d8e641b.png)

I am using one of the test pictures for the display on my phone to see if I can get it to recognize.

**Comment by thehappydinoa** [comment]
@Shankdizzl3 Ok, on the top it appears that you have a import error, I will test it some more, can I ask what version of Android you are on?

**Comment by thehappydinoa** [comment]
@Shankdizzl3 Actually also try the command `adb shell screencap test.png`
`adb pull /sdcard/test.png`

**Comment by Shankdizzl3** [comment]
@thehappydinoa I am currently running version 7.0 on my Android. Once I get home, I will test to see if I am able to screen cap and save to the sd card.

**Comment by thehappydinoa** [comment]
@Shankdizzl3 ok thank you.

**Comment by Shankdizzl3** [comment]
Found a few things while testing. 

First, I attempted to try and screen cap while in the shell and saving it via _screepcap test.png_, but ended up getting an error as seen below. 

![untitled](https://user-images.githubusercontent.com/32983199/37421492-d1d55512-278f-11e8-9f1c-8ae375bf3882.png)

So I attempted to save directly to the SD using _screencap /sdcard/test.png_ and it appeared to be a success, until I tried to find it. What I found was that it was saved to Internal Storage and NOT the SD card. 

![screenshot_20180314-135443](https://user-images.githubusercontent.com/32983199/37421579-0686e352-2790-11e8-9d31-5db453290057.png)

Again, tried to pull the image via _pull test.png_ and received an error. But tried using _pull /sdcard/test.png_ and was successful. 

2:17 PM EST: Update
Was able to get the file opening portion figured out. But still receiving errors when trying to create the file. 

![untitled](https://user-images.githubusercontent.com/32983199/37422762-5bc513be-2792-11e8-9154-6e533eac623b.png)

**Comment by bharathalleni** [comment]
You are on a windows machine. Windows does not allow : as a part of its file name. Please remove the ":" (colon) from the file name of the screenshot and it should work fine

**Comment by Shankdizzl3** [comment]
@bharathalleni That ended up doing it! Good find.

**Comment by thehappydinoa** [comment]
@Shankdizzl3 @bharathalleni @shabbir1215 I believe I have fixed the issue in the last commit, removed the `:` and changed it back to `/sdcard/`. Please let me know. Thank you so much!

**Comment by shabbir1215** [comment]
Thanks
