### ISSUE TITLE
TypeError (NoneType' object has no attribute '__getitem__')

### ISSUE THREAD

**Issue by BuckGup** [thehappydinoa/HQBot#10]
I have followed the guide and it successfully reads the question and makes a request to my google api as I can see the request on my api and services project page but it returns http error 400. It also says TypeError: 'NoneType' object has no attribute '__getitem__'
What's causing this?
https://imgur.com/ZkXrRjg

**Comment by nanip9997** [comment]
ive got the same error make sure you just created your apis correctly or create new ones and try again

**Comment by BuckGup** [comment]
Fixed it as the instructions for this are a bit unclear with what is needed to be done. Now I have another problem though
