### ISSUE TITLE
ServiceUnavailable: 503 Getting metadata from plugin failed with error

### ISSUE THREAD

**Issue by BuckGup** [thehappydinoa/HQBot#11]
When I run the script I am now getting this error

ServiceUnavailable: 503 Getting metadata from plugin failed with error: ('invalid_grant: Invalid JWT Signature.', u'{\n  "error" : "invalid_grant",\n  "error_description" : "Invalid JWT Signature."\n}')

How do I fix this

**Comment by thehappydinoa** [comment]
That means your Json is messed up

**Comment by BuckGup** [comment]
@thehappydinoa In the tutorial you say to download the json but what role should it be? I selected owner but does this even matter? Thanks

**Comment by BuckGup** [comment]
Simply made a new credential with all the roles enabled from the start and that worked.

**Comment by thehappydinoa** [comment]
@BuckGup yay!
