### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by reallat** [thehappydinoa/HQBot#2]
No matter how I try to run it, I used your installation instructions but I get an error:
File "bot.py", line 120
    except ValueError, KeyError:
                     ^
SyntaxError: invalid syntax

**Comment by reallat** [comment]
Or if I use ./bot.py instead of python bot.py, I get 
Traceback (most recent call last):
  File "./bot.py", line 6, in <module>
    import queue
ImportError: No module named queue

**Comment by thehappydinoa** [comment]
@reallat This software should be run by python2

**Comment by reallat** [comment]
Still doesn't work. Running in python 2.7.14 I get  
File "/Users/developeraccount/Desktop/HQBot-master/bot.py", line 4, in <module>
    import six
ImportError: No module named six

**Comment by reallat** [comment]
Actually, I fixed it but I got 
./bot.py -v -i test_question2.png
[~] Filename: ./test_question2.png
[*] Found 10 blocks

[?] Question: What is the act of performing music in public places for tips?

[-] <HttpError 400 when requesting https://www.googleapis.com/customsearch/v1?q=What+is+the+act+of+performing+music+in+public+places+for+tips%3F&alt=json&cx=011154592724722453140%3Achwi_oz7tzq&num=10&key=7d8b1da0be71de6027dea83c84e43bc368824dc3 returned "Bad Request">
[-] NameError: global name 'queue' is not defined

**Comment by thehappydinoa** [comment]
I just fixed this issue in the latest commit
