### ISSUE TITLE
No Answers...

### ISSUE THREAD

**Issue by ghost** [thehappydinoa/HQBot#8]
Hi, sometimes is gets 0 results for every answer and says pick the best. How can I make it search more?

**Comment by thehappydinoa** [comment]
You can actually adjust this in bot.cfg

**Comment by ghost** [comment]
@thehappydinoa How can I do that? Just change the 10 to another number?

**Comment by thehappydinoa** [comment]
Exactly

**Comment by ghost** [comment]
@thehappydinoa When I change it I get errors. I changed it from 10 to 20 or any other number than 10 and get this error. How do I fix it?
![value errrir](https://user-images.githubusercontent.com/11791504/38459796-7ffc475a-3a7c-11e8-87fe-ecbda2b0a73c.JPG)

**Comment by thehappydinoa** [comment]
@johnnyo1012 Add me on Twitter or Discord and we can figure this out...

**Comment by ghost** [comment]
@thehappydinoa Here is my discord. Whats yours or you can add me. 

johnnyo1012
#3200
