### ISSUE TITLE
Please help!! ERROR IN WINDOWS

### ISSUE THREAD

**Issue by nanip9997** [thehappydinoa/HQBot#9]
I ve followed all the instructions in README.MD but i cannot even test the sample questions.Can anyine figure out how i can solve this?
![capture1120](https://user-images.githubusercontent.com/29340053/38481097-b5134c3e-3be6-11e8-8839-cd5843970b09.PNG)

**Comment by thehappydinoa** [comment]
Ah, for windows you have to write `python bot.py`

**Comment by nanip9997** [comment]
it didnt work man !! I thnk its the issue with google custom search api i will recheck whether I have done it correct or not anyone though can help with this!!



![capture1123](https://user-images.githubusercontent.com/29340053/38499938-aab0454a-3c26-11e8-8346-c08a417f2d02.PNG)

**Comment by thehappydinoa** [comment]
@nanip9997 I believe that is a problem with your API setup as mine is working fine...

**Comment by ghost** [comment]
@nanip9997 If someone needs help add me on discord- BionicHuman
#3200

thehappydinoa  helped me fix my issues so I can help anyone else.

**Comment by ghost** [comment]
@nanip9997 @thehappydinoa  Join our discord server for help during trivia game. 

https://discord.gg/87uZscw
